#!/bin/bash
set -uo pipefail

GUARD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/attribution-guard.sh"
MARK='attribution-guard: matched line ->'
fails=0

echo "test -f $GUARD -> $([ -f "$GUARD" ] && echo yes || echo no)"
echo "command -v jq -> $(command -v jq || echo none)"
if [ ! -f "$GUARD" ] || ! command -v jq >/dev/null 2>&1; then
  echo "fail -> not run"
  exit 1
fi

WORK=$(mktemp -d) || { echo "mktemp -d -> exit=$?, not run"; exit 1; }
trap 'rm -rf -- "$WORK"' EXIT
cd "$WORK" || { echo "cd $WORK -> failed, not run"; exit 1; }

FOOT_WITH='Generated with [Claude Code](https://claude.com/claude-code)'
FOOT_BY='_Generated by [Claude Code](https://claude.ai/code)_'
FOOT_LINK='https://claude.ai/code/session_01AbCdEf'
CLEAN='what changed, in one sentence.'

printf '%s\n\n%s\n' "$CLEAN" "$FOOT_WITH" > with.md
printf '%s\n\n---\n%s\n' "$CLEAN" "$FOOT_BY" > by.md
printf '%s\n\n%s\n' "$CLEAN" "$FOOT_LINK" > link.md
printf '%s\n' "$CLEAN" > clean.md

bash_in() { jq -n --arg c "$1" '{tool_name:"Bash",tool_input:{command:$c}}'; }
tool_in() { jq -n --arg b "$1" '{tool_name:"mcp__github__create_pull_request",tool_input:{owner:"o",repo:"r",title:"t",head:"h",base:"main",body:$b}}'; }

run_case() {
  local label=$1 want=$2 input=$3 err got show verdict
  err=$(printf '%s' "$input" | bash "$GUARD" 2>&1 >/dev/null); got=$?
  show="exit=$got"
  verdict=pass
  if [ "$got" -ne "$want" ]; then
    verdict=FAIL
  elif [ "$want" -eq 2 ]; then
    if printf '%s\n' "$err" | grep -a -q -F -- "$MARK"; then
      show="exit=2 carrying the marker"
    else
      show="exit=2 without the marker"
      verdict=FAIL
    fi
  fi
  if [ "$verdict" = FAIL ]; then fails=$((fails + 1)); fi
  echo "$label -> expected exit=$want, actual $show, $verdict"
}

run_case 'gh pr create --body, Generated with' 2 "$(bash_in "gh pr create --title t --body \"$CLEAN

$FOOT_WITH\"")"
run_case 'gh pr create --body, Generated by' 2 "$(bash_in "gh pr create --title t --body \"$CLEAN

$FOOT_BY\"")"
run_case 'gh pr create --body, session link' 2 "$(bash_in "gh pr create --title t --body \"$CLEAN

$FOOT_LINK\"")"
run_case 'gh pr create --body-file with.md' 2 "$(bash_in 'gh pr create --title t --body-file with.md')"
run_case 'gh pr create --body-file by.md' 2 "$(bash_in 'gh pr create --title t --body-file by.md')"
run_case 'gh pr create --body-file link.md' 2 "$(bash_in 'gh pr create --title t --body-file link.md')"
run_case 'gh pr create --body-file=by.md' 2 "$(bash_in 'gh pr create --title t --body-file=by.md')"
run_case 'gh pr edit --body-file by.md' 2 "$(bash_in 'gh pr edit 1 --body-file by.md')"
run_case 'gh pr create -F by.md' 2 "$(bash_in 'gh pr create --title t -F by.md')"
run_case 'gh pr create -F=by.md' 2 "$(bash_in 'gh pr create --title t -F=by.md')"
run_case 'gh pr create -Fby.md' 2 "$(bash_in 'gh pr create --title t -Fby.md')"
run_case 'gh pr create -F "by.md"' 2 "$(bash_in 'gh pr create --title t -F "by.md"')"
run_case 'gh pr edit -F by.md' 2 "$(bash_in 'gh pr edit 1 -F by.md')"
run_case 'gh api .../pulls -F body=@by.md' 2 "$(bash_in 'gh api repos/o/r/pulls -F title=t -F body=@by.md')"
run_case 'pull request tool body, Generated with' 2 "$(tool_in "$CLEAN

$FOOT_WITH")"
run_case 'pull request tool body, Generated by' 2 "$(tool_in "$CLEAN

$FOOT_BY")"
run_case 'pull request tool body, session link' 2 "$(tool_in "$CLEAN

$FOOT_LINK")"
run_case 'gh pr create --body, clean' 0 "$(bash_in "gh pr create --title t --body \"$CLEAN\"")"
run_case 'gh pr create --body-file clean.md' 0 "$(bash_in 'gh pr create --title t --body-file clean.md')"
run_case 'gh pr create -F clean.md' 0 "$(bash_in 'gh pr create --title t -F clean.md')"
run_case 'pull request tool body, clean' 0 "$(tool_in "$CLEAN")"
run_case 'grep for the footer, not a pull request operation' 0 "$(bash_in "grep -n '$FOOT_BY' docs/scripts.md")"
run_case 'input that is not JSON' 0 'not json'

echo "fail -> $fails"
[ "$fails" -eq 0 ]
